relay_servers:
  - "wss://relay-jp.nostr.wirednet.jp"
  - "wss://relay.damus.io"
  - "wss://relay.nostr.wirednet.jp"
  - "wss://nostr.h3z.jp"
  - "wss://relay.snort.social"
  - "wss://nostr-pub.wellorder.net"
  - "wss://relay.current.fyi"
  - "wss://nos.lol"
