version: "3.9"
services:
  nostrchan:
    container_name: nostrchan
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    volumes:
      - "./:/var/bot/"
      - "${HOME}/.gemini:/root/.gemini"
      - "${HOME}/.cache/huggingface:/root/.cache/huggingface"
    ports:
      - "5555:5555"
    tty: true
    working_dir: /var/bot/src
    command: bash -c "cargo run"
    restart: always
