version: "3.9"
services:
  nostrchan:
    container_name: nostrchan
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    volumes:
      - "./:/var/bot/"
    tty: true
    working_dir: /var/bot/src
    command: bash -c "cargo run"
    restart: always

networks:
  default:
    external:
      name: nostify_default
