version: "3.9"
services:
  nostrchan:
    container_name: nostrchan
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    volumes:
      - "./:/var/bot/"
      - "${HOME}/.gemini:/root/.gemini"
    tty: true
    working_dir: /var/bot/src
    command: bash -c "cargo run"
    restart: always
